In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

In [ ]:
df=pd.read_csv('weather_data.csv')

In [ ]:
df.head()

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
0,San Diego,2024-01-14 21:12:46,10.683001,41.195754,4.020119,8.233540
1,San Diego,2024-05-17 15:22:10,8.734140,58.319107,9.111623,27.715161
2,San Diego,2024-05-11 09:30:59,11.632436,38.820175,4.607511,28.732951
3,Philadelphia,2024-02-26 17:32:39,-8.628976,54.074474,3.183720,26.367303
4,San Antonio,2024-04-29 13:23:51,39.808213,72.899908,9.598282,29.898622

In [ ]:
df.head(10)

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
0,San Diego,2024-01-14 21:12:46,10.683001,41.195754,4.020119,8.233540
1,San Diego,2024-05-17 15:22:10,8.734140,58.319107,9.111623,27.715161
2,San Diego,2024-05-11 09:30:59,11.632436,38.820175,4.607511,28.732951
3,Philadelphia,2024-02-26 17:32:39,-8.628976,54.074474,3.183720,26.367303
4,San Antonio,2024-04-29 13:23:51,39.808213,72.899908,9.598282,29.898622
5,San Diego,2024-01-21 08:54:56,27.341055,49.023236,9.166543,27.473896
6,San Jose,2024-01-13 02:10:54,1.881883,65.742325,0.221709,1.073112
7,New York,2024-01-25 19:04:34,-6.894766,30.804894,8.027624,16.848337
8,New York,2024-03-29 05:20:30,0.963545,38.819158,3.640129,7.989024
9,San Jose,2024-05-18 09:14:02,-1.607088,82.198701,4.101493,25.647282

In [ ]:
df.tail()

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
10068,Dallas,2024-04-06 20:48:45,4.421171,30.687766,6.739383,25.468788
10069,San Jose,2024-01-29 05:49:18,2.048257,62.093780,4.237496,28.970039
10070,San Jose,2024-03-14 18:09:08,34.045826,81.313725,2.161628,4.538364
10071,San Diego,2024-02-08 21:12:09,37.541906,36.202676,3.749677,9.298501
10072,New York,2024-04-14 20:46:30,12.722765,80.688138,8.539702,29.000000

In [ ]:
df.tail(10)

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
10063,Philadelphia,2024-01-29 11:49:40,27.465768,87.836625,1.778748,9.962541
10064,New York,2024-02-14 23:58:03,-9.942234,56.239320,5.239598,27.182398
10065,San Jose,2024-04-17 17:34:41,-9.017012,85.074124,0.483819,22.784136
10066,New York,2024-01-25 23:45:15,25.061089,58.488495,7.558824,16.933157
10067,Chicago,2024-05-04 21:23:54,37.157197,76.323932,4.823416,6.236364
10068,Dallas,2024-04-06 20:48:45,4.421171,30.687766,6.739383,25.468788
10069,San Jose,2024-01-29 05:49:18,2.048257,62.093780,4.237496,28.970039
10070,San Jose,2024-03-14 18:09:08,34.045826,81.313725,2.161628,4.538364
10071,San Diego,2024-02-08 21:12:09,37.541906,36.202676,3.749677,9.298501
10072,New York,2024-04-14 20:46:30,12.722765,80.688138,8.539702,29.000000

In [ ]:
df.shape

NameError: name 'df' is not defined

In [ ]:
df.head()