<a href="https://colab.research.google.com/github/AtharvaKhedkar0105/DSBDAPract1/blob/main/DSBDAPract2own.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = {
    'ID':[1,2,3,4,5],
    'Name':['Atharva', 'Kunal', 'Swayam', 'Tejasvi', 'Prem'],
    'Math':[85, 90, np.nan, 66, 125],
    'Science':[78, 88, 92, None, 65],
    'English':[80, 85, 70, 60, 75],
    'Attendance':[0.92, 0.85, 0.95, 0.40, 1.10]
}

In [4]:
print(data)

{'ID': [1, 2, 3, 4, 5], 'Name': ['Atharva', 'Kunal', 'Swayam', 'Tejasvi', 'Prem'], 'Math': [85, 90, nan, 66, 125], 'Science': [78, 88, 92, None, 65], 'English': [80, 85, 70, 60, 75], 'Attendance': [0.92, 0.85, 0.95, 0.4, 1.1]}

In [5]:
df = pd.DataFrame(data)

In [6]:
print(df)

   ID     Name   Math  Science  English  Attendance
0   1  Atharva   85.0     78.0       80        0.92
1   2    Kunal   90.0     88.0       85        0.85
2   3   Swayam    NaN     92.0       70        0.95
3   4  Tejasvi   66.0      NaN       60        0.40
4   5     Prem  125.0     65.0       75        1.10

In [7]:
df.isnull().sum()

ID            0
Name          0
Math          1
Science       1
English       0
Attendance    0
dtype: int64

In [8]:
df.dtypes

ID              int64
Name           object
Math          float64
Science       float64
English         int64
Attendance    float64
dtype: object

In [9]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.describe()

             ID        Math    Science    English  Attendance  Math_log
count  5.000000    5.000000   5.000000   5.000000    5.000000  5.000000
mean   3.000000   86.500000  81.200000  74.000000    0.824000  4.450725
std    1.581139   12.668859  10.473777   9.617692    0.243167  0.157155
min    1.000000   66.000000  65.000000  60.000000    0.400000  4.189655
25%    2.000000   85.000000  78.000000  70.000000    0.850000  4.442651
50%    3.000000   90.000000  83.000000  75.000000    0.920000  4.499810
75%    4.000000   91.500000  88.000000  80.000000    0.950000  4.516339
max    5.000000  100.000000  92.000000  85.000000    1.000000  4.605170

In [11]:
df.loc[len(df)] = df.loc[1]

In [13]:
df

   ID     Name   Math  Science  English  Attendance
0   1  Atharva   85.0     78.0       80        0.92
1   2    Kunal   90.0     88.0       85        0.85
2   3   Swayam    NaN     92.0       70        0.95
3   4  Tejasvi   66.0      NaN       60        0.40
4   5     Prem  125.0     65.0       75        1.10
5   2    Kunal   90.0     88.0       85        0.85

In [14]:
df[df.duplicated(subset=['Math'])]

   ID   Name  Math  Science  English  Attendance
5   2  Kunal  90.0     88.0       85        0.85

In [15]:
df = df.drop_duplicates().copy()

In [16]:
df

   ID     Name   Math  Science  English  Attendance
0   1  Atharva   85.0     78.0       80        0.92
1   2    Kunal   90.0     88.0       85        0.85
2   3   Swayam    NaN     92.0       70        0.95
3   4  Tejasvi   66.0      NaN       60        0.40
4   5     Prem  125.0     65.0       75        1.10

In [17]:
df['Math'] = df['Math'].fillna(df['Math'].mean())

/tmp/ipykernel_1199/1038178227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Math'] = df['Math'].fillna(df['Math'].mean())

In [18]:
df

   ID     Name   Math  Science  English  Attendance
0   1  Atharva   85.0     78.0       80        0.92
1   2    Kunal   90.0     88.0       85        0.85
2   3   Swayam   91.5     92.0       70        0.95
3   4  Tejasvi   66.0      NaN       60        0.40
4   5     Prem  125.0     65.0       75        1.10

In [19]:
df['Science'] = df['Science'].fillna(df['Science'].median())

/tmp/ipykernel_1199/368293247.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Science'] = df['Science'].fillna(df['Science'].median())

In [20]:
df

   ID     Name   Math  Science  English  Attendance
0   1  Atharva   85.0     78.0       80        0.92
1   2    Kunal   90.0     88.0       85        0.85
2   3   Swayam   91.5     92.0       70        0.95
3   4  Tejasvi   66.0     83.0       60        0.40
4   5     Prem  125.0     65.0       75        1.10

In [21]:
def attend(x):
    return min(x, 1)

df['Attendance'] = df['Attendance'].apply(attend)

/tmp/ipykernel_1199/3976859995.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Attendance'] = df['Attendance'].apply(attend)

In [22]:
df

   ID     Name   Math  Science  English  Attendance
0   1  Atharva   85.0     78.0       80        0.92
1   2    Kunal   90.0     88.0       85        0.85
2   3   Swayam   91.5     92.0       70        0.95
3   4  Tejasvi   66.0     83.0       60        0.40
4   5     Prem  125.0     65.0       75        1.00

In [23]:
df['Math'] = df['Math'].apply(lambda x: min(x, 100))

/tmp/ipykernel_1199/1324181280.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Math'] = df['Math'].apply(lambda x: min(x, 100))

In [24]:
df

   ID     Name   Math  Science  English  Attendance
0   1  Atharva   85.0     78.0       80        0.92
1   2    Kunal   90.0     88.0       85        0.85
2   3   Swayam   91.5     92.0       70        0.95
3   4  Tejasvi   66.0     83.0       60        0.40
4   5     Prem  100.0     65.0       75        1.00

In [25]:
df['Math'].min()

66.0

In [26]:
df['Math_log']=np.log(df['Math'])

/tmp/ipykernel_1199/1209941809.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Math_log']=np.log(df['Math'])

In [27]:
df

   ID     Name   Math  Science  English  Attendance  Math_log
0   1  Atharva   85.0     78.0       80        0.92  4.442651
1   2    Kunal   90.0     88.0       85        0.85  4.499810
2   3   Swayam   91.5     92.0       70        0.95  4.516339
3   4  Tejasvi   66.0     83.0       60        0.40  4.189655
4   5     Prem  100.0     65.0       75        1.00  4.605170